version: '3.9'

services:

  api-service:
    container_name: api-service
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '80:7749'
    networks:
      - backend

networks:
  backend:
    driver: bridge
